import test from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {databaseConfig} from '../src/config.mjs';
import {digest} from '../../../packages/hosted-routing/src/result.ts';
import {productionAuthority} from '../src/production-authority.mjs';
import {PostgresDispatchStore} from '../src/postgres-dispatch.mjs';
import {PostgresVerificationStore} from '../src/postgres-verification.mjs';
import {PostgresSpendLedger} from '../src/postgres-spend.mjs';
import {CloudWorkControl} from '../src/cloud-work-control.mjs';
import {productionSpendPlan} from '../src/production-execution-plan.mjs';
import {productionVerifierPolicy as policy,productionVerifierPolicySha256 as policySha256} from '../src/production-verifier-policy.mjs';
import {validationConfiguration as configuration,validationContractSha256 as contractSha256,validationCandidateSha256 as candidateSha256,validationSourceGrant as grant} from '../src/production-validation-plan.mjs';

test('CONNECTED production exact authority consumption, immutable grant, concurrent claims and verifier revocation',{skip:process.env.FACTORY_POSTGRES_TEST!=='1'},async t=>{
 const url=new URL(process.env.DATABASE_URL_UNPOOLED);assert(['localhost','127.0.0.1'].includes(url.hostname),'Disposable localhost only');
 const pool=new pg.Pool({...databaseConfig(url.href),max:5}),schema='factory_authority_'+randomUUID().replaceAll('-','');
 await pool.query('CREATE SCHEMA '+schema);
 const rewrite=sql=>sql.replace(/\bfactory\.(production_work_authority|protect_production_authority|work_spend_budgets|work_spend_operations|intake_receipts|delivery_intents|verification_resources|execution_resources|candidate_custody|work_orders|runs|events)\b/g,schema+'.$1').replace(/IN SCHEMA factory\b/g,'IN SCHEMA '+schema);
 t.after(async()=>{await pool.query('DROP SCHEMA '+schema+' CASCADE');await pool.end();});
 const query=(sql,args)=>pool.query(rewrite(sql),args),isolated={connect:async()=>{const c=await pool.connect();return{query:(sql,args)=>c.query(rewrite(sql),args),release:()=>c.release()};}};
 for(const file of ['002-canonical-execution-ledger','004-canonical-dispatch','005-cloud-custody','006-cloud-verification','008-production-work-authority'])await query(await readFile(new URL('../migrations/'+file+'.sql',import.meta.url),'utf8'));
 const installation={ownerScope:'disposable-production-owner'},sourceDigest='a'.repeat(64),configurationDigest=digest(configuration),factoryVersion=digest({sourceDigest,configurationDigest});
 const request={protocol:'MYFACTORY_EXECUTION_V2',requestId:randomUUID(),workId:randomUUID(),workGeneration:1,repository:grant.source.repository,source:grant.source,deadline:new Date(Date.now()+170000).toISOString(),maxSpendUsd:1,input:{title:'Disposable exact validation',description:'Exercise release authority only',kind:'feature',acceptanceCriteria:['Exact custody'],allowedPaths:grant.allowedPaths,checkCommands:grant.commands}};
 const manifest={version:1,clientId:grant.clientId,ownerScope:installation.ownerScope,sourceDigest,configurationDigest,factoryVersion,contractSha256,candidateSha256,environment:'CLOUD_PRODUCTION',publication:false,request};
 await query("INSERT INTO factory.production_work_authority(request_id,work_id,client_id,manifest,manifest_sha256,state) VALUES($1,$2,$3,$4,$5,'AUTHORIZED')",[request.requestId,request.workId,grant.clientId,manifest,digest(manifest)]);
 const assertAuthority=productionAuthority({installation,sourceDigest,configuration,contractSha256,clientId:grant.clientId,candidateSha256});
 const store=new PostgresDispatchStore(isolated,{maxWorks:1,custodyPrefix:'factory/production',verificationPolicySha256:policySha256,assertAuthority}),spend=new PostgresSpendLedger(isolated),verification=new PostgresVerificationStore(store,{policy,policySha256});
 const control=new CloudWorkControl({store,spend,grant:{...grant,ownerScope:installation.ownerScope},configuration,sourceDigest,signing:{factoryId:'myfactory-cloud-production'},executionSpendPlan:productionSpendPlan,verificationPolicy:{policy,policySha256}});
 const [one,two]=await Promise.all([control.prepare(request),control.prepare(request)]);assert.equal(one.runId,two.runId);
 assert.equal((await query('SELECT count(*) FROM factory.intake_receipts')).rows[0].count,'1');
 assert((await query('SELECT consumed_at FROM factory.production_work_authority')).rows[0].consumed_at);
 await assert.rejects(query("UPDATE factory.production_work_authority SET manifest=manifest||'{\"publication\":true}'"),/immutable/);
 await assert.rejects(query('DELETE FROM factory.production_work_authority'),/cannot be deleted/);
 await assert.rejects(control.prepare({...request,requestId:randomUUID()}),/NOT_AUTHORIZED/);
 const identity={runId:randomUUID(),dispatchIdentity:randomUUID(),writerGeneration:1,workId:request.workId,workGeneration:1,requestId:request.requestId,repository:request.repository,deadline:request.deadline,baseSha:grant.source.commit,allowedPaths:grant.allowedPaths,factoryId:one.snapshot.factoryId,factoryVersion,workOrderId:one.workOrderId,remoteRunId:one.runId};
 await spend.bindAuthority({workId:request.workId,workGeneration:1,requestId:request.requestId,workOrderId:one.workOrderId,dispatchIdentity:identity.dispatchIdentity,factoryVersion,runId:one.runId});
 const claims=await Promise.all([store.claim(grant.clientId,identity),store.claim(grant.clientId,identity)]);assert.equal(claims.filter(Boolean).length,1);
 const lease=claims.find(Boolean);await store.recordAllocation(one.runId,lease.lease_owner,lease.lease_generation,'sbx_disposable_producer');
 await store.confirmCleanup(one.runId,lease.lease_owner,lease.lease_generation,'sbx_disposable_producer');
 await query("UPDATE factory.execution_resources SET evidence='{\"visibleChecksPassed\":true}' WHERE run_id=$1",[one.runId]);
 await query('INSERT INTO factory.candidate_custody(run_id,candidate_commit,candidate_tree,artifact_sha256,artifact_path,artifact_bytes) VALUES($1,$2,$3,$4,$5,1)',[one.runId,'a'.repeat(40),'b'.repeat(40),'c'.repeat(64),'disposable-local-only']);
 const admitted=await verification.claim(grant.clientId,request.requestId);assert.equal(admitted.created,true);
 await verification.allocated(one.runId,admitted.record.lease_owner,'sbx_disposable_verifier');
 await verification.assertActive(one.runId,admitted.record.lease_owner);
 await store.transaction(c=>c.query("UPDATE factory.production_work_authority SET state='REVOKED' WHERE request_id=$1",[request.requestId]));
 await assert.rejects(verification.assertActive(one.runId,admitted.record.lease_owner),/NOT_AUTHORIZED/);
 await assert.rejects(verification.finish(one.runId,admitted.record.lease_owner,policy.checks.map(c=>({id:c.id,result:'PASS'}))),/NOT_AUTHORIZED/);
 assert.equal((await verification.read(grant.clientId,request.requestId)).outcome,'UNKNOWN');
 await verification.failed(one.runId,admitted.record.lease_owner,'VERIFIER_AUTHORITY_REVOKED');await verification.cleanup(one.runId,admitted.record.lease_owner,'sbx_disposable_verifier');
 assert.equal((await verification.read(grant.clientId,request.requestId)).cleanup_confirmed,true);
 await assert.rejects(query("UPDATE factory.production_work_authority SET state='AUTHORIZED'"),/immutable/);
 assert.equal((await query('SELECT count(*) FROM factory.work_spend_operations')).rows[0].count,'0');
});
