import test from 'node:test';import assert from 'node:assert/strict';import pg from 'pg';import{randomUUID}from'node:crypto';import{readFile}from'node:fs/promises';
import{fixture as rosterFixture}from'./fixtures/alpha-owner.mjs';import{alphaOwnerBinding,alphaRecordScope}from'../src/alpha-owner-roster.mjs';import{productionAuthority}from'../src/production-authority.mjs';import{successorIntakePolicy,assertSuccessorPredecessor}from'../src/production-successor-intake.mjs';import{PostgresDispatchStore}from'../src/postgres-dispatch.mjs';import{PostgresSpendLedger}from'../src/postgres-spend.mjs';import{CloudWorkControl}from'../src/cloud-work-control.mjs';import{productionConfiguration as configuration,productionSourceGrant,productionSpendPlan,productionExecutionContractSha256 as contractSha256}from'../src/production-execution-plan.mjs';import{productionVerifierPolicy as policy,productionVerifierPolicySha256 as policySha256}from'../src/production-verifier-policy.mjs';import{digest}from'../../../packages/hosted-routing/src/result.ts';
const url=process.env.FACTORY_PAID_TEST_DATABASE_URL;
test('LOCAL one exact successor intake preserves lifetime history and paid authority fencing',{skip:!url},async t=>{
 assert(['localhost','127.0.0.1'].includes(new URL(url).hostname));const pool=new pg.Pool({connectionString:url,max:8}),schemas=[];t.after(async()=>{for(const schema of schemas)await pool.query('DROP SCHEMA '+schema+' CASCADE');await pool.end()});
 async function setup(){
  const schema='successor_'+randomUUID().replaceAll('-','');await pool.query('CREATE SCHEMA '+schema);schemas.push(schema);
  const rewrite=s=>s.replaceAll("'factory.","'EVENTPREFIX.").replace(/\bfactory\./g,schema+'.').replace(/IN SCHEMA factory\b/g,'IN SCHEMA '+schema).replaceAll("'EVENTPREFIX.","'factory."),query=(s,a)=>pool.query(rewrite(s),a),isolated={connect:async()=>{const c=await pool.connect();return{query:(s,a)=>c.query(rewrite(s),a),release:()=>c.release()}}};
  for(const version of ['002-canonical-execution-ledger','004-canonical-dispatch','005-cloud-custody','006-cloud-verification','008-production-work-authority','009-paid-operation-release','010-three-owner-authority'])await query(await readFile(new URL('../migrations/'+version+'.sql',import.meta.url),'utf8'));
  const{env}=rosterFixture(),binding=alphaOwnerBinding(env,'sofie-alpha-a'),sourceDigest='a'.repeat(64),configurationDigest=digest(configuration),factoryVersion=digest({sourceDigest,configurationDigest}),grant={...productionSourceGrant,clientId:binding.clientId,ownerScope:binding.ownerScope};
  async function make({successor,workId=randomUUID(),requestId=randomUUID(),generation=2,expired=false,owner=binding}={}){
   const request={protocol:'MYFACTORY_EXECUTION_V2',requestId,workId,workGeneration:generation,repository:grant.source.repository,source:grant.source,deadline:new Date(Date.now()+(expired?-1000:160000)).toISOString(),maxSpendUsd:1,input:{title:'Successor fixture',description:'No provider calls',kind:'feature',acceptanceCriteria:['One additional admission'],allowedPaths:grant.allowedPaths,checkCommands:grant.commands}};
   const template={version:1,clientId:owner.clientId,ownerScope:owner.ownerScope,sourceDigest,configurationDigest,factoryVersion,contractSha256,candidateSha256:null,environment:'CLOUD_PRODUCTION',publication:false,request:{...request,requestId:null,deadline:null}};
   const envelope={version:1,expiresAt:new Date(Date.now()+300000).toISOString(),approval:{workVersion:2,configurationHash:'c'.repeat(64),ownerBinding:owner,manifestTemplate:template,...(successor?{successorIntake:{...successor,workId,workGeneration:generation}}:{})}},approved=digest(envelope),manifest={...template,version:2,request,authorizationEnvelope:envelope,authorizationEnvelopeSha256:approved};
   await query("INSERT INTO factory.production_work_authority(request_id,work_id,client_id,manifest,manifest_sha256,state) VALUES($1,$2,$3,$4,$5,'AUTHORIZED')",[requestId,workId,owner.clientId,manifest,digest(manifest)]);
   const authority=productionAuthority({installation:{ownerScope:owner.ownerScope},sourceDigest,configuration,contractSha256,clientId:owner.clientId,authorizationSha256:approved,ownerBinding:owner}),store=new PostgresDispatchStore(isolated,{maxWorks:1,workLimitError:'PRODUCTION_CANARY_WORK_LIMIT',custodyPrefix:'factory/production',verificationPolicySha256:policySha256,assertAuthority:authority,assertRecordScope:alphaRecordScope(owner)}),spend=new PostgresSpendLedger(isolated),control=new CloudWorkControl({store,spend,grant:{...grant,clientId:owner.clientId},configuration,sourceDigest,signing:{factoryId:'myfactory-cloud-production'},executionSpendPlan:productionSpendPlan,verificationPolicy:{policy,policySha256}});
   const identity=row=>({runId:randomUUID(),writerGeneration:1,dispatchIdentity:randomUUID(),workId,workGeneration:generation,factoryId:'myfactory-cloud-production',factoryVersion,requestId,workOrderId:row.work_order_id,remoteRunId:row.run_id,repository:request.repository,baseSha:request.source.commit,allowedPaths:grant.allowedPaths,deadline:request.deadline});
   async function claim(){const row=await store.read(owner.clientId,requestId),i=identity(row);await spend.bindAuthority({workId:i.workId,workGeneration:i.workGeneration,requestId:i.requestId,workOrderId:i.workOrderId,runId:i.remoteRunId,dispatchIdentity:i.dispatchIdentity,factoryVersion:i.factoryVersion});return{row,i,resource:await store.claim(owner.clientId,i)}}
   return{request,manifest,envelope,control,store,authority,claim};
  }
  const old=await make();await old.control.prepare(old.request);const{row,i,resource}=await old.claim();await old.store.recordAllocation(row.run_id,resource.lease_owner,resource.lease_generation,'sbx_local');await old.store.stop(binding.clientId,i);await old.store.confirmCleanup(row.run_id,resource.lease_owner,resource.lease_generation,'sbx_local');await old.store.finalize(binding.clientId,old.request.requestId,'CANCELLED');await query("UPDATE factory.production_work_authority SET state='REVOKED' WHERE request_id=$1",[old.request.requestId]);
  const predecessor={requestId:row.request_id,workId:row.work_id,workGeneration:row.work_generation,runId:row.run_id,inputDigest:row.input_digest,manifestSha256:digest(old.manifest)},successor={version:1,clientId:binding.clientId,maxIntakes:1,predecessor};
  return{query,isolated,make,old,predecessor,successor,binding,env,history:JSON.stringify((await query('SELECT * FROM factory.intake_receipts')).rows)};
 }
 await t.test('concurrent exact replay produces one successor; claim/model remain usable at count two; third denied',async()=>{
  const f=await setup(),next=await f.make({successor:f.successor});const [a,b]=await Promise.all([next.control.prepare(next.request),next.control.prepare(next.request)]);assert.equal(a.runId,b.runId);assert.equal((await f.query('SELECT count(*) FROM factory.intake_receipts')).rows[0].count,'2');assert((await next.claim()).resource);await next.store.transaction(c=>next.authority(c,next.request,Date.now(),'model'));
  assert.equal(JSON.stringify((await f.query('SELECT * FROM factory.intake_receipts WHERE request_id=$1',[f.old.request.requestId])).rows),f.history);
  const third=await f.make({successor:f.successor});await assert.rejects(third.control.prepare(third.request),/WORK_LIMIT/);assert.equal((await f.query('SELECT consumed_at FROM factory.production_work_authority WHERE request_id=$1',[third.request.requestId])).rows[0].consumed_at,null);
  await assert.rejects(f.old.control.prepare(f.old.request),/AUTHORIZED/);
 });
 await t.test('different simultaneous requests cannot each consume the same remaining intake',async()=>{
  const f=await setup(),a=await f.make({successor:f.successor}),b=await f.make({successor:f.successor});const results=await Promise.allSettled([a.control.prepare(a.request),b.control.prepare(b.request)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await f.query('SELECT count(*) FROM factory.intake_receipts')).rows[0].count,'2');
 });
 await t.test('no exception, stale generation, revoked, expired and B/C/personal cannot consume',async()=>{
  const f=await setup();for(const opts of [{},{generation:1,successor:f.successor},{expired:true,successor:f.successor},...['sofie-alpha-b','sofie-alpha-c'].map(id=>({owner:alphaOwnerBinding(f.env,id),successor:f.successor}))]){const n=await f.make(opts);await assert.rejects(n.control.prepare(n.request),/WORK_LIMIT|BINDING|AUTHORIZED/);}
  const n=await f.make({successor:f.successor});await f.query("UPDATE factory.production_work_authority SET state='REVOKED' WHERE request_id=$1",[n.request.requestId]);await assert.rejects(n.control.prepare(n.request),/AUTHORIZED/);
  const a=structuredClone(n.envelope.approval);a.manifestTemplate.clientId='sofie-production';assert.throws(()=>successorIntakePolicy(a),/BINDING/);assert.equal((await f.query('SELECT count(*) FROM factory.intake_receipts')).rows[0].count,'1');
 });
 await t.test('predecessor digest, roster, cleanup and paid activity fail closed',async()=>{
  const f=await setup(),n=await f.make({successor:f.successor});for(const patch of [{inputDigest:'f'.repeat(64)},{manifestSha256:'f'.repeat(64)},{runId:randomUUID()},{workId:n.request.workId}]){const a=structuredClone(n.envelope.approval);Object.assign(a.successorIntake.predecessor,patch);await assert.rejects(assertSuccessorPredecessor({query:f.query},a),/SUCCESSOR/);}
  const a=structuredClone(n.envelope.approval);a.ownerBinding.rosterSha256='e'.repeat(64);await assert.rejects(assertSuccessorPredecessor({query:f.query},a),/PREDECESSOR/);
  await f.query('UPDATE factory.execution_resources SET cleanup_confirmed=false WHERE run_id=$1',[f.predecessor.runId]);await assert.rejects(n.control.prepare(n.request),/UNRESOLVED/);await f.query('UPDATE factory.execution_resources SET cleanup_confirmed=true WHERE run_id=$1',[f.predecessor.runId]);
  const old=(await f.query('SELECT * FROM factory.intake_receipts WHERE request_id=$1',[f.predecessor.requestId])).rows[0];
  await f.query(`INSERT INTO factory.work_spend_operations(operation_id,work_id,work_generation,dispatch_identity,request_id,work_order_id,factory_version,run_id,model,pricing_revision,reserved_microusd,actual_microusd,state,created_at,updated_at,phase) VALUES($1,$2,2,$3,$4,$5,$6,$7,'fixture','fixture',1,1,'settled','now','now','productive')`,[randomUUID(),old.work_id,randomUUID(),old.request_id,old.work_order_id,'a'.repeat(64),old.run_id]);
  await assert.rejects(n.control.prepare(n.request),/UNRESOLVED/);
  assert.equal((await f.query('SELECT consumed_at FROM factory.production_work_authority WHERE request_id=$1',[n.request.requestId])).rows[0].consumed_at,null);
 });
 await t.test('revocation wins under the same dispatch lock; no intake or consumed grant remains',async()=>{
  const f=await setup(),n=await f.make({successor:f.successor}),c=await f.isolated.connect();await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(81427603)');const pending=n.control.prepare(n.request);await c.query("UPDATE factory.production_work_authority SET state='REVOKED' WHERE request_id=$1",[n.request.requestId]);await c.query('COMMIT');c.release();await assert.rejects(pending,/AUTHORIZED/);assert.equal((await f.query('SELECT count(*) FROM factory.intake_receipts')).rows[0].count,'1');
 });
});
